import { Injectable, NestMiddleware } from "@nestjs/common";

import { randomUUID } from "crypto";
import type { NextFunction, Request, Response } from "express";

/**
 * Extracts or generates a Request-ID for every incoming HTTP request.
 *
 * Flow:
 * 1. Read `X-Request-ID` from the incoming request header (generated by the
 *    mobile/web client's Axios interceptor).
 * 2. Fall back to a server-generated UUID if none is present.
 * 3. Attach the ID to `req.requestId` so services can include it in log lines.
 * 4. Echo the same ID in the response `X-Request-ID` header so the client can
 *    match Sentry breadcrumbs to backend log entries.
 *
 * Register globally in `AppModule.configure()`.
 *
 * @see BEST_PRACTICES.md §5 (Request-ID Middleware) and §13 (End-to-End Tracing)
 */
@Injectable()
export class RequestIdMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: NextFunction): void {
    const incoming = req.headers["x-request-id"];
    const requestId =
      typeof incoming === "string" && incoming.length > 0
        ? incoming
        : randomUUID();

    // Attach to request so downstream services can access it.
    req.requestId = requestId;

    // Echo back to the client.
    res.setHeader("X-Request-ID", requestId);

    next();
  }
}
